name: Deploy to VPS

on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show workspace files
        run: |
          pwd
          ls -la
          echo "----"
          find . -maxdepth 3 -type f

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          debug: true
          source: "index.html,css,img,js,favicon.ico"
          target: "/var/www/portfolio"
          rm: true
